export const fiatCurrencies=[
  {currency_name:"United States Dollar ($)", currency_code:"USD"},
  {currency_name:"Chilean Peso ($)",currency_code:"CLP"},
  {currency_name:"Colombian Peso (Col$)", currency_code:"COP"},
  {currency_name:"Indian Rupee (₹)",currency_code:"INR"},
  {currency_name:"Mexican Peso ($)",currency_code:"MXN"},
  {currency_name:"Peruvian Sol (S/)", currency_code:"PEN"}]
  /* {currency_name:"Saudi Riyal (ر.س)",currency_code:"SAR"},
  {currency_name:"Swiss Franc (Fr)",currency_code:"CHF"},
  {currency_name:"Kuwaiti Dinar (د.ك)",currency_code:"KWD"},
  {currency_name:"Pound Sterling (£)",currency_code:"GBP"},
  {currency_name:"Canadian Dollar ($)",currency_code:"CAD"},
  {currency_name:"Euro (€)",currency_code:"EUR"},
  {currency_name:"Brazilian Real (R$)",currency_code:"BRL"},
  {currency_name:"United Arab Emirates Dirham (د.إ)",currency_code:"AED"},
  {currency_name:"Argentine Peso ($)",currency_code:"ARS"},
  {currency_name:"Australian Dollar ($)",currency_code:"AUD"},
  {currency_name:"Bahraini Dinar (.د.ب)",currency_code:"BHD"},
  {currency_name:"Cambodian Riel (៛)",currency_code:"KHR"},
  {currency_name:"Costa Rican Colón (₡)",currency_code:"CRC"},
  {currency_name:"Dominican Peso ($)",currency_code:"DOP"},
  {currency_name:"Hong Kong Dollar ($)",currency_code:"HKD"},
  {currency_name:"Indonesian Rupiah (Rp)",currency_code:"IDR"},
  {currency_name:"Japanese Yen (¥)",currency_code:"JPY"},
  {currency_name:"Malaysian Ringgit (RM)",currency_code:"MYR"},
  {currency_name:"Namibian Dollar ($)",currency_code:"NAD"},
  {currency_name:"New Zealand Dollar ($)",currency_code:"NZD"},
  {currency_name:"Nigerian Naira (₦)",currency_code:"NGN"},
  {currency_name:"Pakistani Rupee (₨)",currency_code:"PKR"},
  {currency_name:"Philippine Peso (₱)",currency_code:"PHP"},
  {currency_name:"Singapore Dollar (S$)",currency_code:"SGD"},
  {currency_name:"South African Rand (R)",currency_code:"ZAR"},
  {currency_name:"Sri Lankan Rupee (Rs)",currency_code:"LKR"},
  {currency_name:"Thai Baht (฿)",currency_code:"THB"},
  {currency_name:"Ugandan Shilling (Sh)",currency_code:"UGX"},
  {currency_name:"Vietnamese Dong (₫)",currency_code:"VND"},
  {currency_name:"Guatemalan Quetzal (Q)",currency_code:"GTQ"},
  {currency_name:"Nepalese Rupee (₨)",currency_code:"NPR"} */
